# Generated by Django 5.2.18 on 2026-10-07 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=80, unique=True)),
                ('specialization', models.CharField(max_length=160)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)])),
                ('bio', models.TextField(blank=True)),
                ('is_accepting_appointments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='clinics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='clinics.doctorprofile')),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
                'indexes': [models.Index(fields=['doctor', 'weekday', 'is_active'], name='clinics_doc_doctor__c46a4b_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time'), name='unique_doctor_weekday_start'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='doctor_availability_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='clinics.doctorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'date'], name='clinics_sch_doctor__220273_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'date'), name='unique_doctor_schedule_exception_date'), models.CheckConstraint(condition=models.Q(('is_closed', True), models.Q(('start_time__isnull', False), ('end_time__isnull', False), ('end_time__gt', models.F('start_time'))), _connector='OR'), name='open_exception_requires_valid_hours')],
            },
        ),
    ]
