# Generated by Django 5.2.18 on 2026-10-07 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='doctor_availability_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='doctorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gte', 5), ('slot_duration_minutes__lte', 240)), name='doctor_slot_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='doctorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('consultation_fee__gte', 0)), name='doctor_consultation_fee_nonnegative'),
        ),
    ]
