# Generated by Django 5.2.18 on 2026-10-07 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_patients(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    PatientProfile = apps.get_model("patients", "PatientProfile")
    existing_user_ids = PatientProfile.objects.values_list("user_id", flat=True)
    patients = User.objects.filter(role="patient").exclude(pk__in=existing_user_ids)
    PatientProfile.objects.bulk_create(
        [PatientProfile(user_id=user_id) for user_id in patients.values_list("pk", flat=True)]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__last_name', 'user__first_name', 'user__email'),
            },
        ),
        migrations.RunPython(create_profiles_for_existing_patients, migrations.RunPython.noop),
    ]
