# Generated by Django 5.2.18 on 2026-10-07 17:59

from django.db import migrations, models


def trust_existing_staff_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.exclude(role="patient").update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            trust_existing_staff_accounts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
