# Generated by Django 5.2.18 on 2026-10-07 19:37

import django.db.models.deletion
from django.db import migrations, models


def seed_example_medicines(apps, schema_editor):
    Medicine = apps.get_model("prescriptions", "Medicine")
    examples = (
        ("Paracetamol", "Paracetamol", "250 mg", "tablet"),
        ("Paracetamol", "Paracetamol", "500 mg", "tablet"),
        ("Paracetamol", "Paracetamol", "650 mg", "tablet"),
        ("Amoxicillin", "Amoxicillin", "500 mg", "capsule"),
    )
    for name, generic_name, strength, dosage_form in examples:
        Medicine.objects.using(schema_editor.connection.alias).get_or_create(
            name=name,
            strength=strength,
            dosage_form=dosage_form,
            defaults={"generic_name": generic_name},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='food_timing',
            field=models.CharField(blank=True, choices=[('before_food', 'Before food'), ('after_food', 'After food'), ('with_food', 'With food'), ('any', 'Any time')], max_length=16),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('generic_name', models.CharField(blank=True, max_length=180)),
                ('strength', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=80)),
                ('manufacturer', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'strength'),
                'indexes': [models.Index(fields=['name', 'strength'], name='prescriptio_name_deed10_idx'), models.Index(fields=['generic_name'], name='prescriptio_generic_3b04c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'strength', 'dosage_form'), name='unique_medicine_product')],
            },
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='prescriptions.medicine'),
        ),
        migrations.RunPython(seed_example_medicines, migrations.RunPython.noop),
    ]
