# Generated by Django 5.2.18 on 2026-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescriptionitem_food_timing_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='route',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
