# Generated by Django 5.2.18 on 2026-10-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_medicine_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
